artifact_location: file:///C:/Users/user/Desktop/Product_Management_system/.mlruns/0
creation_time: 1775571942748
experiment_id: '0'
last_update_time: 1775571942748
lifecycle_stage: active
name: Default
workspace: default
